### ISSUE TITLE
Temp issue

### ISSUE THREAD

**Issue by kabir** [kabir/play-action-test#1]
```
name: XNIO + remoting
components:
  - name: xnio
    org: kabir
    branch: '3.8'
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: kabir
    branch: '5.0'
    mavenOpts: -DskipTests
    dependencies:
      - name: xnio
        property: xnio.version
```
